package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"golang/graph/model"
)

// CreateSignup is the resolver for the createSignup field.
func (r *mutationResolver) CreateSignup(ctx context.Context, input model.NewUser) (*model.User, error) {
	return r.Svc.UserSignup(input)
}

// CreateCompany is the resolver for the createCompany field.
func (r *mutationResolver) CreateCompany(ctx context.Context, input model.NewCompany) (*model.Company, error) {
	return r.Svc.CreateCompany(input)
}

// CreateJob is the resolver for the createJob field.
func (r *mutationResolver) CreateJob(ctx context.Context, input model.NewJob) (*model.Job, error) {
	return r.Svc.CreateJob(input)
}

// ViewAllCompanies is the resolver for the viewAllCompanies field.
func (r *queryResolver) ViewAllCompanies(ctx context.Context) ([]*model.Company, error) {
	return r.Svc.ViewAllCompanies()
}

// ViewCompanyByID is the resolver for the viewCompanyById field.
func (r *queryResolver) ViewCompanyByID(ctx context.Context, cid string) (*model.Company, error) {
	return r.Svc.ViewCompanyByID(cid)
}

// ViewAllJobs is the resolver for the viewAllJobs field.
func (r *queryResolver) ViewAllJobs(ctx context.Context) ([]*model.Job, error) {
	return r.Svc.ViewAllJobs()
}

// ViewJobByID is the resolver for the viewJobById field.
func (r *queryResolver) ViewJobByID(ctx context.Context, id string) (*model.Job, error) {
	return r.Svc.ViewJobByID(id)
}

// ViewJobByCid is the resolver for the viewJobByCid field.
func (r *queryResolver) ViewJobByCid(ctx context.Context, cid string) ([]*model.Job, error) {
	return r.Svc.ViewJobByCid(cid)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
